// Sample doctors data - Make sure this loads first
const doctorsData = [
  {
    id: 1,
    name: "Dr. Rajesh Kumar Sharma",
    specialization: "Cardiologist",
    qualification: "MBBS, MD (Cardiology), DM (Cardiology)",
    experience: 15,
    rating: 4.8,
    phone: "+91-9876543210",
    email: "rajesh.sharma@email.com",
    address: "Apollo Hospital, Sector 26, Near City Center Mall",
    city: "New Delhi",
    state: "Delhi",
    consultationFee: 800,
    imageUrl: "../images/male doc 1.webp",
    availableDays: "Mon-Sat",
    availableTime: "10:00 AM - 6:00 PM",
    about:
      "Dr. Rajesh Kumar Sharma is a renowned cardiologist with over 15 years of experience in treating heart conditions. He specializes in interventional cardiology and has performed over 2000 successful procedures.",
  },
  {
    id: 2,
    name: "Dr. Priya Patel",
    specialization: "Dermatologist",
    qualification: "MBBS, MD (Dermatology)",
    experience: 8,
    rating: 4.6,
    phone: "+91-9876543211",
    email: "priya.patel@email.com",
    address: "Fortis Hospital, Andheri West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    consultationFee: 600,
    imageUrl: "../images/female doc 1.webp",
    availableDays: "Mon-Fri",
    availableTime: "9:00 AM - 5:00 PM",
    about:
      "Dr. Priya Patel is a skilled dermatologist specializing in cosmetic dermatology and skin cancer treatment. She has helped thousands of patients achieve healthy, beautiful skin.",
  },
  {
    id: 3,
    name: "Dr. Amit Singh",
    specialization: "Orthopedic Surgeon",
    qualification: "MBBS, MS (Orthopedics)",
    experience: 12,
    rating: 4.7,
    phone: "+91-9876543212",
    email: "amit.singh@email.com",
    address: "Max Hospital, Golf Course Road, Sector 38",
    city: "Gurgaon",
    state: "Haryana",
    consultationFee: 900,
    imageUrl: "../images/male doc 2.jpg",
    availableDays: "Mon-Sat",
    availableTime: "8:00 AM - 7:00 PM",
    about:
      "Dr. Amit Singh is an experienced orthopedic surgeon specializing in joint replacement and sports medicine. He has successfully treated numerous athletes and patients with complex orthopedic conditions.",
  },
  {
    id: 4,
    name: "Dr. Sunita Reddy",
    specialization: "Pediatrician",
    qualification: "MBBS, MD (Pediatrics)",
    experience: 10,
    rating: 4.9,
    phone: "+91-9876543213",
    email: "sunita.reddy@email.com",
    address: "Rainbow Children Hospital, Banjara Hills",
    city: "Hyderabad",
    state: "Telangana",
    consultationFee: 500,
    imageUrl: "../images/female doc 2.jpg",
    availableDays: "Mon-Sun",
    availableTime: "9:00 AM - 8:00 PM",
    about:
      "Dr. Sunita Reddy is a compassionate pediatrician with extensive experience in child healthcare. She specializes in newborn care and childhood development disorders.",
  },
  {
    id: 5,
    name: "Dr. Vikram Gupta",
    specialization: "Neurologist",
    qualification: "MBBS, MD (Medicine), DM (Neurology)",
    experience: 18,
    rating: 4.5,
    phone: "+91-9876543214",
    email: "vikram.gupta@email.com",
    address: "AIIMS, Ansari Nagar East",
    city: "New Delhi",
    state: "Delhi",
    consultationFee: 1000,
    imageUrl: "../images/male doc 3.jpeg",
    availableDays: "Mon-Fri",
    availableTime: "10:00 AM - 4:00 PM",
    about:
      "Dr. Vikram Gupta is a leading neurologist specializing in stroke treatment and epilepsy management. He has published numerous research papers in international journals.",
  },
  {
    id: 6,
    name: "Dr. Kavitha Nair",
    specialization: "Gynecologist",
    qualification: "MBBS, MS (Obstetrics & Gynecology)",
    experience: 14,
    rating: 4.8,
    phone: "+91-9876543215",
    email: "kavitha.nair@email.com",
    address: "Manipal Hospital, HAL Airport Road",
    city: "Bangalore",
    state: "Karnataka",
    consultationFee: 700,
    imageUrl: "https://images.unsplash.com/photo-1527613426441-4da17471b66d",
    availableDays: "Mon-Sat",
    availableTime: "9:00 AM - 6:00 PM",
    about:
      "Dr. Kavitha Nair is an experienced gynecologist specializing in high-risk pregnancies and minimally invasive gynecological procedures.",
  },
]

console.log("✅ Data loaded successfully! Found", doctorsData.length, "doctors")
